<Project>
  <PropertyGroup>
    <Version>1.0.0</Version>
    <Company>FileMerge</Company>
    <Product>FileMerge</Product>
    <Copyright>Copyright (c) 2026 FileMerge contributors</Copyright>
    <RepositoryUrl>https://github.com/hiro5791/FileMerge</RepositoryUrl>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>
  </PropertyGroup>
</Project>
